version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "dev_db"
      POSTGRES_USER: "dev_admin"
      POSTGRES_PASSWORD: "dev_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_admin -d dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    links: 
      - bot
  bot:
    image: reeezos/cyberyulia:0.0.1
    ports:
      - "7000:7000"
      - "80:80"
    links: 
      - postgres
